services:
  - type: web
    name: ced-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BASIC_B64
        sync: false
      - key: UNIDADE_ID
        sync: false
      - key: OM_BASE
        sync: false
      - key: CHATPRO_TOKEN
        sync: false
      - key: DISCORD_WEBHOOK
        sync: false
      - key: CHATPRO_URL
        sync: false

  - type: web
    name: ced-site
    runtime: static
    buildCommand: 'echo "Static build"'
    staticPublishPath: "./"
